version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: portal_db_dev
    environment:
      POSTGRES_DB: portal_db
      POSTGRES_USER: portal_user
      POSTGRES_PASSWORD: WerZxc2000VB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: portal_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev: