# Generated by Django 6.0.2 on 2026-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_text_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')]),
        ),
    ]
