# Generated by Django 6.0.2 on 2026-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reject_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
