# Generated by Django 6.0.2 on 2026-03-31 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_avatar_profile_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scientific_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='CreatorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('scientific_interests', models.TextField()),
                ('vk_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('reject_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на Creator',
                'verbose_name_plural': 'Заявки на Creator',
                'ordering': ['-created_at'],
            },
        ),
    ]
