# Generated by Django 6.0.2 on 2026-04-12 02:48

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0008_sectionmaterialimage'),
        ('posts', '0013_post_reject_comment'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='education.course')),
            ],
            options={
                'verbose_name': 'Эмбеддинг курса',
            },
        ),
        migrations.CreateModel(
            name='PostEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='posts.post')),
            ],
            options={
                'verbose_name': 'Эмбеддинг постов',
            },
        ),
        migrations.CreateModel(
            name='SectionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='education.educationsection')),
            ],
            options={
                'verbose_name': 'Эмбеддинг раздела',
            },
        ),
    ]
