# Generated by Django 6.0.2 on 2026-03-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_reject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
