# Generated by Django 6.0.2 on 2026-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_category_educationsection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
