# Generated by Django 6.0.2 on 2026-03-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reject_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
