# Generated by Django 6.0.2 on 2026-02-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmaterial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='education.educationsection'),
        ),
    ]
