# Generated by Django 6.0.2 on 2026-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_sectionmaterial_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='educationsection',
            name='is_published',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('moderation', 'На модерации'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='educationsection',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('moderation', 'На модерации'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
