# Generated by Django 6.0.2 on 2026-03-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_course_rating_course_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsection',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
