# Generated by Django 6.0.2 on 2026-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_course_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationsection',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
