# Generated by Django 6.0.2 on 2026-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_educationsection_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
