# Generated by Django 6.0.2 on 2026-03-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='if_partial',
            new_name='is_partial',
        ),
    ]
