# Generated by Django 6.0.2 on 2026-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='points_earned',
            field=models.FloatField(default=0),
        ),
    ]
